name: Feature Request
description: Suggest an enhancement or new feature for the CAN package
title: '[FEATURE] '
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please describe your idea clearly and explain the use case.

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: Clear description of the feature you're requesting
      placeholder: What would you like to see added to the package?
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case / Problem Solved
      description: Why do you need this feature? What problem does it solve?
      placeholder: Explain the use case and benefit of this feature
    validations:
      required: true

  - type: textarea
    id: example-usage
    attributes:
      label: Example Usage
      description: How would this feature be used?
      placeholder: |
        ```typescript
        // Example code showing how the feature would be used
        ```
      render: typescript
    validations:
      required: false

  - type: textarea
    id: can-relation
    attributes:
      label: Related to CAN System
      description: Is this related to the Official CAN Guide specification?
      placeholder: |
        Related CAN codes or concepts:
        Link to Official CAN Guide section (if applicable):
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Before Submitting
      options:
        - label: I have searched for existing feature requests
          required: false
        - label: This is a package feature, not a CAN system specification question
          required: false
        - label: I understand this feature should align with the Official CAN Guide
          required: false
